module.exports = [
  {
    name: "AI-based Wellness Band",
    description: "Tracks calories, hydration, stress, and sleep with AI-powered insights.",
    price: "₹8,499",
    category: "Health_Devices",
    image: "/images/AI-based_Wellness_Band.jpg",
    inStock: "yes",
    rating: "4.6",
  },
  {
    name: "Bandage Tape",
    description: "Flexible medical tape for dressing and securing bandages in place.",
    price: "₹120",
    category: "Health_Devices",
    image: "/images/bandage_tape.jpg",
    inStock: "yes",
    rating: "4.2",
  },
  {
    name: "Continous glucose monitors",
    description: "Wearable sensor for 24/7 glucose tracking, ideal for diabetic care.",
    price: "₹4,999",
    category: "Health_Devices",
    image: "/images/continous_glucose_monitors.jpeg",
    inStock: "yes",
    rating: "4.7",
  },
  {
    name: "Digital Blood Pressure Monitor",
    description: "Cuff-based automatic device to track blood pressure at home.",
    price: "₹2,199",
    category: "Health_Devices",
    image: "/images/Digital_Blood_Pressure_Monitor.jpg",
    inStock: "yes",
    rating: "4.5",
  },
  {
    name: "ECG + Digital Stethoscope Combo",
    description: "Portable 2-in-1 device to monitor heart rhythms and lung sounds.",
    price: "₹9,999",
    category: "Health_Devices",
    image: "/images/ECG_Digital_Stethoscope_Combo.jpeg",
    inStock: "yes",
    rating: "4.4",
  },
  {
    name: "Fitness Ttracker",
    description: "Lightweight wristband to track steps, sleep, and heart rate.",
    price: "₹3,999",
    category: "Health_Devices",
    image: "/images/firness_tracker.webp",
    inStock: "yes",
    rating: "4.3",
  },
  {
    name: "Ingestible Digital pill",
    description: "Sensor-enabled pill to monitor medication ingestion and digestion.",
    price: "₹6,500",
    category: "Health_Devices",
    image: "/images/Ingestible_Digital_pill.jpeg",
    inStock: "yes",
    rating: "4.6",
  },
  {
    name: "Oura Ring",
    description: "Compact smart ring to track sleep, recovery, and readiness.",
    price: "₹21,000",
    category: "Health_Devices",
    image: "/images/Oura_Ring.jpg",
    inStock: "yes",
    rating: "4.8",
  },
  {
    name: "Pulse Oximeter",
    description: "Compact device to measure blood oxygen saturation and pulse rate.",
    price: "₹799",
    category: "Health_Devices",
    image: "/images/Pulse_Oximeter.jpeg",
    inStock: "yes",
    rating: "4.5",
  },
  {
    name: "Remote Patient Monitoring Kit",
    description: "All-in-one kit for home-based vitals monitoring including BP, pulse, and temp.",
    price: "₹14,500",
    category: "Health_Devices",
    image: "/images/Remote_Patient_Monitoring_Kit",
    inStock: "yes",
    rating: "4.7",
  },
  {
    name: "Smart Belt",
    description: "Tracks posture, waist size, and activity through a fashionable belt.",
    price: "₹6,299",
    category: "Health_Devices",
    image: "/images/Smart_Belt.jpeg",
    inStock: "yes",
    rating: "4.2",
  },
  {
    name: "Smart Clothing",
    description: "Sensor-embedded wearables for ECG, motion, and respiratory monitoring.",
    price: "₹7,999",
    category: "Health_Devices",
    image: "/images/Smart_Clothing.webp",
    inStock: "yes",
    rating: "4.4",
  },
  {
    name: "Smart Hearing Aid",
    description: "Advanced hearing aid with Bluetooth and AI noise cancellation.",
    price: "₹29,999",
    category: "Health_Devices",
    image: "/images/Smart_Hearing_Aid.jpeg",
    inStock: "yes",
    rating: "4.6",
  },
  {
    name: "Smart Hydration Bottle",
    description: "Tracks daily water intake and reminds you to stay hydrated.",
    price: "₹2,500",
    category: "Health_Devices",
    image: "/images/Smart_Hydration_Bottle.jpeg",
    inStock: "yes",
    rating: "4.3",
  },
  {
    name: "Smart Jewelry",
    description: "Stylish wearable to track steps, sleep, stress, and fertility.",
    price: "₹5,500",
    category: "Health_Devices",
    image: "/images/Smart_Jewelry.avif",
    inStock: "yes",
    rating: "4.4",
  },
  {
    name: "Smart Patch",
    description: "Wearable patch for continuous monitoring of vital signs.",
    price: "₹4,999",
    category: "Health_Devices",
    image: "/images/Smart_Patch.webp",
    inStock: "yes",
    rating: "4.5",
  },
  {
    name: "Smart Ring (NFC enabled)",
    description: "Health-focused ring with step tracker, NFC payments, and notifications.",
    price: "₹3,899",
    category: "Health_Devices",
    image: "/images/Smart_Ring.jpg",
    inStock: "yes",
    rating: "4.1",
  },
  {
    name: "Smart Thermometer",
    description: "Fast and accurate thermometer with Bluetooth connectivity.",
    price: "₹1,199",
    category: "Health_Devices",
    image: "/images/Smart_Thermometer.jpg",
    inStock: "yes",
    rating: "4.4",
  },
  {
    name: "Smartwatch with Health Sensor",
    description: "Multifunction smartwatch with ECG, SPO2, and heart monitoring.",
    price: "₹12,000",
    category: "Health_Devices",
    image: "/images/Smartwatch_with_Health_Sensor.webp",
    inStock: "yes",
    rating: "4.6",
  },
  {
    name: "Wearable ECG Monitor",
    description: "Wrist-worn device providing medical-grade ECG and heart rhythm analysis.",
    price: "₹9,999",
    category: "Health_Devices",
    image: "/images/Wearable_ECG_Monitor.jpg",
    inStock: "yes",
    rating: "4.5",
  },
  {
    name: "Wearable Stress Sensor",
    description: "Detects stress via skin conductance and alerts you to breathe or relax.",
    price: "₹4,699",
    category: "Health_Devices",
    image: "/images/Wearable_Stress_Sensor.jpg",
    inStock: "yes",
    rating: "4.3",
  },
];
